// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBssqmLI34fhaQ5YwpuTGxaoPjY7L7U8AY',
    appId: '1:742967502512:web:24937031a07228fe5afd75',
    messagingSenderId: '742967502512',
    projectId: 'elderwatchtest',
    authDomain: 'elderwatchtest.firebaseapp.com',
    databaseURL:
        'https://elderwatchtest-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elderwatchtest.firebasestorage.app',
    measurementId: 'G-ZSHGKL0MRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjjTTK2J8WzJXo9SltPlYVhUZ6TzQMpj4',
    appId: '1:742967502512:android:b3bfe949267ba9a95afd75',
    messagingSenderId: '742967502512',
    projectId: 'elderwatchtest',
    databaseURL:
        'https://elderwatchtest-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elderwatchtest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcvBSJA5fI3nk1FEOxmND8a_rFfVODUEY',
    appId: '1:742967502512:ios:b6385139ea499be25afd75',
    messagingSenderId: '742967502512',
    projectId: 'elderwatchtest',
    databaseURL:
        'https://elderwatchtest-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elderwatchtest.firebasestorage.app',
    iosBundleId: 'com.example.projectApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcvBSJA5fI3nk1FEOxmND8a_rFfVODUEY',
    appId: '1:742967502512:ios:b6385139ea499be25afd75',
    messagingSenderId: '742967502512',
    projectId: 'elderwatchtest',
    databaseURL:
        'https://elderwatchtest-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elderwatchtest.firebasestorage.app',
    iosBundleId: 'com.example.projectApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBssqmLI34fhaQ5YwpuTGxaoPjY7L7U8AY',
    appId: '1:742967502512:web:b8425fcc9b16186f5afd75',
    messagingSenderId: '742967502512',
    projectId: 'elderwatchtest',
    authDomain: 'elderwatchtest.firebaseapp.com',
    databaseURL:
        'https://elderwatchtest-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elderwatchtest.firebasestorage.app',
    measurementId: 'G-E6P2DEW0RV',
  );
}
